version: "3.9"

services:
  db:
    container_name: postgresql_quiz
    image: postgres:15.1-alpine
    restart: always
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - quiz_app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pg_data:

networks:
  quiz_app_network:
